services:

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
     - '${SMTP_PORT:-1025}:1025'
     - '${WEB_MAIL_PORT:-8025}:8025'

  postgres:
      image: postgres:latest
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgresPasswword}
        - POSTGRES_USER=${POSTGRES_USER:-nodeProdUser}
        - POSTGRES_DB=${POSTGRES_DB:-nest_starter}
      ports:
        - '${POSTGRES_PORT:-5432}:5432'
   
  rabbitmq:
    image: rabbitmq:3.12-management  # Includes the management UI
    restart: unless-stopped
    ports:
      - "${AMQP_PORT:-5672}:5672"  # AMQP protocol port
      - "${AMQP_UI:-15672}:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    volumes:
      - ./tmp/db/rabbitmq:/var/lib/rabbitmq

  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT:-6379}:6379'

    volumes:
      - './tmp/db/redis:/bitnami/redis/data'
  
      
