name: nest-starter
services:

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
     - '${SMTP_PORT:-1025}:1025'
     - '${WEB_MAIL_PORT:-8025}:8025'

  postgres:
      container_name: postgres
      image: postgres:latest
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=nest_starter
      ports:
        - '${POSTGRES_PORT:-5432}:5432'
      # postgresql://nodeProdUser:postgresPasswword@localhost:5433/nest_starter
      
  # sonarqube:
  #    image: sonarqube:community
  #    ports:
  #       - '9000:9000'
  #    environment:
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
  
      
